In [2]:
import numpy as np
import csv
import pandas as pd


In [3]:
file_train = 'ATIS.txt'
file_test = 'ATIS_RAWTEST.txt'


In [176]:
sent_no = []
word = []
tags = []
with open(file_train) as fil:
    l = fil.readline()
#     print(l.split('\t'))
    while l : 
        splits = l.split('\t')
        sent_no.append(splits[0])
        word.append(splits[1])
        tags.append(splits[2])
#         print(l)
        l = fil.readline()


In [177]:
intents = []

print(tags[0].split('#')[1].lstrip())
for ta in tags:
    if ta == '':
        continue
    else:
        intents.append(ta.split('#')[1].lstrip())

flight


In [178]:
words = []
for w in word:
    words.append(w.split("#")[1].lstrip())

In [179]:
sentences = []
# intents = []
for i in range(len(words)):
    if words[i] == "BOS":
        i = i + 1
        # start extracting the sentence
        sent = ''
        while words[i] != "EOS":
            sent = sent + " " + words[i]
            i = i + 1
        sentences.append(sent)
    

In [180]:
print(len(intents)) ## y 
print(len(sentences)) ## X

9956
9956


In [181]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.preprocessing.text import text_to_word_sequence

In [182]:
vocab = " ".join(sentences)
print(set(text_to_word_sequence(vocab)))
vocab_size = len(set(text_to_word_sequence(vocab)))
print(vocab_size)

{'takeoffs', 'live', 'ac', 'please', 'guardia', 'fourth', 'return', 'later', 'local', 'stand', 'dollars', '400', 'oh', '98', 'fifth', 'departs', 'taxi', 'minnesota', 'transcontinental', '466', 'ticket', 'sa', 'just', 'longest', 'lax', 'afterwards', '459', 'reverse', 'instead', '1110', 's', 'nashville', 'they', 'bur', 'anywhere', 'rate', 'near', 'need', 'florida', 'same', '755', 'as', '932', 'airports', 'far', 'lunch', 'fifteen', 'cheap', '305', 'tower', 'via', 'trying', 'when', 'cover', 'don', 'a', 'west', 'some', 'book', 'very', '720', 'kinds', 'us', 'visit', 'where', 'thirteenth', 'more', 'm', '137338', 'highest', '230', 'thursdays', 'hou', 'ohio', 'wish', 'see', 'fares', 'planes', 'economic', 'michigan', 'carries', '1600', '1020', 'los', 'scheduled', 'fridays', 'travels', 'come', 'mco', 'soon', 'give', '2134', 'georgia', '4', 'seven', '201', '813', 'meal', 'itinerary', '1765', '343', 'discount', 'who', 'traveling', 'off', 'philly', 'bay', '718', 'cleveland', 'sixteen', '928', 'rent'

In [183]:
from keras.preprocessing.text import Tokenizer
t = Tokenizer()
t.fit_on_texts(sentences)

In [184]:

# summarize what was learned
print(t.word_counts)
print(t.document_count)
print(t.word_index)
print(t.word_docs)


OrderedDict([('i', 1994), ('want', 314), ('to', 8616), ('fly', 548), ('from', 7432), ('boston', 2140), ('at', 324), ('838', 10), ('am', 256), ('and', 1572), ('arrive', 282), ('in', 1710), ('denver', 1984), ('1110', 4), ('the', 4190), ('morning', 576), ('what', 2692), ('flights', 4866), ('are', 916), ('available', 382), ('pittsburgh', 1374), ('baltimore', 1236), ('on', 2990), ('thursday', 288), ('is', 1328), ('arrival', 10), ('time', 84), ('san', 2008), ('francisco', 1736), ('for', 552), ('755', 4), ('flight', 2342), ('leaving', 628), ('washington', 680), ('cheapest', 418), ('airfare', 36), ('tacoma', 84), ('orlando', 178), ('round', 404), ('trip', 436), ('fares', 348), ('philadelphia', 1176), ('under', 22), ('1000', 52), ('dollars', 102), ('need', 404), ('a', 1800), ('tomorrow', 138), ('columbus', 62), ('minneapolis', 94), ('kind', 58), ('of', 764), ('aircraft', 138), ('used', 64), ('cleveland', 136), ('dallas', 1306), ('show', 2108), ('me', 2522), ('los', 130), ('angeles', 130), ('all

In [185]:
X  = t.texts_to_matrix(sentences, mode='count')

print(X)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [186]:
no_intents = len(set(intents))
uniq_intents = list(set(intents))

In [187]:
t1 = Tokenizer()
t1.fit_on_texts(intents)
y  = t1.texts_to_matrix(intents, mode='count')

In [188]:
# print(uniq_intents)
intents_no = []
for i in intents:
    intents_no.append(uniq_intents.index(i))

In [190]:
y = to_categorical(intents_no)
# print(y_test.shape)
# # y_test.append(np.zeros(y_test.shape[0]))
# y_t = np.zeros((893,19))
# for i,t in enumerate(y_test):
#     print(t)
#     y_t[i] = t[:19]
# print(X_test.shape)

In [192]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)

In [195]:
model = Sequential()
model.add(Dense(units = 100, activation='relu',input_dim = X_train.shape[1]))
model.add(Dense(units = y_train.shape[1], activation = 'softmax'))


In [196]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [197]:
model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
8960/8960 [==============================] - 1s 59us/step - loss: 1.4804 - acc: 0.7044
Epoch 2/100
8960/8960 [==============================] - 0s 33us/step - loss: 0.9877 - acc: 0.7350
Epoch 3/100
8960/8960 [==============================] - 0s 36us/step - loss: 0.8691 - acc: 0.7502
Epoch 4/100
8960/8960 [==============================] - 0s 33us/step - loss: 0.7818 - acc: 0.7923
Epoch 5/100
8960/8960 [==============================] - 0s 35us/step - loss: 0.7134 - acc: 0.8213
Epoch 6/100
8960/8960 [==============================] - 0s 33us/step - loss: 0.6584 - acc: 0.8390
Epoch 7/100
8960/8960 [==============================] - 0s 35us/step - loss: 0.6135 - acc: 0.8558
Epoch 8/100
8960/8960 [==============================] - 0s 35us/step - loss: 0.5755 - acc: 0.8644
Epoch 9/100
8960/8960 [==============================] - 0s 34us/step - loss: 0.5430 - acc: 0.8728
Epoch 10/100
8960/8960 [==============================] - 0s 35us/step - loss: 0.5143 - acc: 0.8776
Epoch 11/

8960/8960 [==============================] - 0s 34us/step - loss: 0.1002 - acc: 0.9823
Epoch 84/100
8960/8960 [==============================] - 0s 39us/step - loss: 0.0989 - acc: 0.9827
Epoch 85/100
8960/8960 [==============================] - 0s 36us/step - loss: 0.0975 - acc: 0.9827
Epoch 86/100
8960/8960 [==============================] - 0s 36us/step - loss: 0.0963 - acc: 0.9836
Epoch 87/100
8960/8960 [==============================] - 0s 33us/step - loss: 0.0950 - acc: 0.9838
Epoch 88/100
8960/8960 [==============================] - 0s 31us/step - loss: 0.0937 - acc: 0.9838
Epoch 89/100
8960/8960 [==============================] - 0s 32us/step - loss: 0.0925 - acc: 0.9837
Epoch 90/100
8960/8960 [==============================] - 0s 31us/step - loss: 0.0914 - acc: 0.9843
Epoch 91/100
8960/8960 [==============================] - 0s 33us/step - loss: 0.0902 - acc: 0.9847
Epoch 92/100
8960/8960 [==============================] - 0s 31us/step - loss: 0.0891 - acc: 0.9848
Epoch 93/100


In [199]:
loss_and_metrics = model.evaluate(X_test, y_test, batch_size=128)
print("Loss : {}\nAccuracy : {}".format(loss_and_metrics[0], loss_and_metrics[1]))

996/996 [==============================] - 0s 25us/step
Loss : 0.12350403233225565
Accuracy : 0.9728915650681799


In [249]:
import random
random.randint(10,10)

10