In [155]:
import random
from Final import *
from make_puzzle import generate_puzzle
%load_ext autoreload

%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [105]:
# Cell to check the validity of the actions
# s = execute_action(goal, 0)[0]
# print(s)
# s1 = execute_action(s, 0)[0]
# print(s1)
# s1 = execute_action(s1, 1)[0]
# print(s1)
# s1 = execute_action(s1, 1)[0]
# print(s1)
# s1 = execute_action(s1, 3)[0]
# print(s1)
# s1 = execute_action(s1, 3)[0]
# print(s1)


# s1 = execute_action(s1, 2)[0]
# print(s1)

# s1 = execute_action(s1, 2)[0]
# print(s1)

In [130]:
start_state = "./start.txt" # this will contain the start the state of the agnet
end_state = "./end.txt" # this file will contain the end or goal state of the agent

state = np.zeros((3,3)).astype(int)
goal =  np.zeros((3,3)).astype(int)

# to read the starting state of the game
with open(start_state) as fil:
    # read the fule
    row = 0 # the currebt row
    line = fil.readline()
    while line:
        for col,no in enumerate(line.split()):
            state[row][col] = no
        line = fil.readline()
        row = row + 1
# to read the goal state of the game
with open(end_state) as fil:
    # read the goal state
    row = 0 # the currebt row
    line = fil.readline()
    while line:
        for col,no in enumerate(line.split()):
            goal[row][col] = no
        line = fil.readline()
        row = row + 1

In [150]:
start_state = generate_puzzle(goal, steps= 50)

True


In [151]:
print(start_state)

[[6 3 4]
 [1 5 2]
 [7 0 8]]


In [156]:
run_experiment(start_state, goal, h3)


Success Found Path
States Explored : 262
Iterations Requried to Reach Success : 160



In [157]:
run_experiment(start_state, goal, h2)

Success Found Path
States Explored : 628
Iterations Requried to Reach Success : 375



In [158]:
run_experiment(start_state, goal, h1)

Success Found Path
States Explored : 8858
Iterations Requried to Reach Success : 5481



In [102]:
def print_path(all_states , parent, parent_index):
	'''
	parent : It is the dictionary containing index and parents
	parent_index :  teh dindex of the p[arent]
	'''
	if parent_index == -1:
		return
	print_path(all_states, parent, parent[parent_index])
	print("{}\n".format(all_states[parent_index]))
	

In [104]:
print_path(all_states, parent, goal_index)

[[4. 1. 2.]
 [7. 5. 3.]
 [8. 6. 0.]]

[[4. 1. 2.]
 [7. 5. 3.]
 [8. 0. 6.]]

[[4. 1. 2.]
 [7. 5. 3.]
 [0. 8. 6.]]

[[4. 1. 2.]
 [0. 5. 3.]
 [7. 8. 6.]]

[[0. 1. 2.]
 [4. 5. 3.]
 [7. 8. 6.]]

[[1. 0. 2.]
 [4. 5. 3.]
 [7. 8. 6.]]

[[1. 2. 0.]
 [4. 5. 3.]
 [7. 8. 6.]]

[[1. 2. 3.]
 [4. 5. 0.]
 [7. 8. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 0.]]



In [108]:
all_states

[array([[4., 1., 6.],
        [7., 5., 3.],
        [2., 0., 8.]]), array([[4., 1., 6.],
        [7., 0., 3.],
        [2., 5., 8.]]), array([[4., 1., 6.],
        [7., 5., 3.],
        [0., 2., 8.]]), array([[4., 1., 6.],
        [7., 5., 3.],
        [2., 8., 0.]]), array([[4., 1., 6.],
        [7., 5., 0.],
        [2., 8., 3.]]), array([[4., 1., 6.],
        [0., 5., 3.],
        [7., 2., 8.]]), array([[4., 1., 0.],
        [7., 5., 6.],
        [2., 8., 3.]]), array([[4., 1., 6.],
        [7., 0., 5.],
        [2., 8., 3.]]), array([[4., 0., 6.],
        [7., 1., 3.],
        [2., 5., 8.]]), array([[4., 1., 6.],
        [0., 7., 3.],
        [2., 5., 8.]]), array([[4., 1., 6.],
        [7., 3., 0.],
        [2., 5., 8.]]), array([[0., 1., 6.],
        [4., 5., 3.],
        [7., 2., 8.]]), array([[4., 1., 6.],
        [5., 0., 3.],
        [7., 2., 8.]]), array([[4., 0., 1.],
        [7., 5., 6.],
        [2., 8., 3.]]), array([[4., 0., 6.],
        [7., 1., 5.],
        [2., 8., 3