In [6]:
import random
import numpy as np

In [45]:
from keras.models import Sequential
from keras.layers import Dense


model = Sequential()
model.add(Dense(units = 2, activation='sigmoid',input_dim = 2))
model.add(Dense(units = 2, activation = 'softmax'))

In [46]:
model.compile(loss = 'categorical_crossentropy', 
             optimizer = 'sgd',
             metrics = ['accuracy'])


In [47]:
n = 10000 # ddataset size
x = [[random.randint(0,1),random.randint(0,1)] for i in range(n)]
y = [i^j for i,j in x]
x = np.array(x)
y = np.reshape(y, (-1,1))
from keras.utils import to_categorical
y = to_categorical(y)
print(x)
print(y)

[[1 0]
 [1 1]
 [1 1]
 ...
 [0 1]
 [0 0]
 [1 1]]
[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [48]:
model.fit(x, y, epochs = 6, batch_size = 1)

Epoch 1/6
10000/10000 [==============================] - 6s 555us/step - loss: 0.6708 - acc: 0.6076
Epoch 2/6
10000/10000 [==============================] - 5s 536us/step - loss: 0.3620 - acc: 0.8955
Epoch 3/6
10000/10000 [==============================] - 5s 547us/step - loss: 0.0738 - acc: 1.0000
Epoch 4/6
10000/10000 [==============================] - 5s 535us/step - loss: 0.0322 - acc: 1.0000
Epoch 5/6
10000/10000 [==============================] - 5s 536us/step - loss: 0.0201 - acc: 1.0000
Epoch 6/6
10000/10000 [==============================] - 6s 614us/step - loss: 0.0145 - acc: 1.0000


In [49]:
model.predict(x)

array([[0.01621307, 0.983787  ],
       [0.98977435, 0.01022561],
       [0.98977435, 0.01022561],
       ...,
       [0.01106914, 0.9889309 ],
       [0.9872399 , 0.01276013],
       [0.98977435, 0.01022561]], dtype=float32)